name: Verify

on:
  pull_request:
    branches: [ pr/optimize-workflows ]

jobs:
  verify:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Free some disk space on runner
      run: |
        df -h
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/share/boost
        sudo rm -rf /usr/lib/jvm
        sudo rm -rf /usr/lib/firefox
        sudo rm -rf /opt/microsoft/powershell
        sudo rm -rf /opt/hostedtoolcache
        echo "free space after cleanup:"
        df -h

    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: go cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Get dependencies
      run: go mod download

    - name: Verify
      run: |
        make verify
